# Generated by Django 5.2.6 on 2025-09-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trains",
                to="train_station.traintype",
            ),
        ),
    ]
